### ISSUE TITLE
type of progress bar 

### ISSUE THREAD

**Issue by khajer** [khajer/minpgb#3]
add more type of progress

**Comment by Eshan-Agarwal** [comment]
I want to pick this , can you explain more about it ?

**Comment by khajer** [comment]
currently , progress bar look like 
[#######                ] 
i want to try set another format 
[*************          ]
[==========>      ]
[----->                    ]

with 
```
pb := pgb.New()
pb.style = pbg.STYLE_1 
//or 
pb.SetStyle(pbg.STYLE_1)
```
